name: Salt Docker Image CI (GitHub actions)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: docker-compose build
    
    - name: Configure
      run: docker-compose up -d
    
    - name: Test
      run: docker-compose exec -T salt-master salt '*' test.ping
